services:
  pyspark:
    build:
      context: .
      dockerfile: dockerfile
    container_name: pyspark311-jdk17
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - .:/opt/app
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      PYSPARK_PYTHON: /usr/local/bin/python
      MPLBACKEND: Agg
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser
      --ServerApp.root_dir=/opt/app
